### ISSUE TITLE
Unit test and mocking issue

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#150]
Sometimes after a code cahnge I  have an issue. Don't understand that is the root cause.

Most likely it is related to conf file parsers.

```
$ ./unittests.sh
........................Traceback (most recent call last):
  File "/Users/dmitry/env/dvc/bin/nosetests", line 11, in <module>
    load_entry_point('nose==1.3.7', 'console_scripts', 'nosetests')()
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 75, in run
    test(result)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/case.py", line 138, in run
    result.addError(self, err)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/proxy.py", line 132, in addError
    self.result.addError(self.test, self._prepareErr(err))
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/result.py", line 61, in addError
    exc_info = self._exc_info_to_string(err, test)
  File "/Users/dmitry/env/dvc/lib/python2.7/site-packages/nose/result.py", line 187, in _exc_info_to_string
    return _TextTestResult._exc_info_to_string(self, err, test)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/result.py", line 164, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 101, in extract_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/Users/dmitry/env/dvc/bin/../lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/Users/dmitry/env/dvc/bin/../lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/Users/dmitry/env/dvc/bin/../lib/python2.7/linecache.py", line 131, in updatecache
    with open(fullname, 'rU') as fp:
AttributeError: StringIO instance has no attribute '__exit__'
```

**Comment by efiop** [comment]
This is a nosetests bug and I've also seen it triggered by some of our tests failing. Try running individual tests(i.e. by adding tests/test_name.py to the end of nosetests line in unittests.sh) and you will be able to see the error more clearly.

**Comment by dmpetrov** [comment]
I've found that it is related to `TestConfigTest`. Tests `aws_credentials_specified_test` and `aws_credentials_default_test`.

It looks like `mock` uses some hacks that `nosetests` doesn't understand.

Possible workaround - instead of mocking IO we can just temporary reproduce the entire environment with real files.

I'm disabling these tests for now.

**Comment by efiop** [comment]
No longer relevant with new internal design and unit tests.
