### ISSUE TITLE
version conflicts for dependencies

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#173]
after installing the latest version from master, when running the program, I get error messages about bad versions for some of the packages

for example:
```
$ dvc                                                                                                                                                                                          15:46:21
Traceback (most recent call last):
  File "/Users/ophir/miniconda3/envs/dvc/bin/dvc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (oauth2client 4.1.2 (/Users/ophir/miniconda3/envs/dvc/lib/python2.7/site-packages), Requirement.parse('oauth2client<4.0dev,>=2.0.0'), set(['gapic-google-cloud-spanner-v1', 'gapic-google-cloud-logging-v2', 'proto-google-cloud-spanner-v1', 'gapic-google-cloud-datastore-v1', 'gapic-google-cloud-vision-v1', 'gapic-google-cloud-pubsub-v1', 'gapic-google-cloud-speech-v1beta1', 'proto-google-cloud-pubsub-v1', 'proto-google-cloud-error-reporting-v1beta1', 'proto-google-cloud-logging-v2', 'proto-google-cloud-spanner-admin-database-v1', 'gapic-google-cloud-error-reporting-v1beta1', 'gapic-google-cloud-spanner-admin-instance-v1', 'proto-google-cloud-spanner-admin-instance-v1', 'proto-google-cloud-datastore-v1', 'proto-google-cloud-vision-v1', 'gapic-google-cloud-spanner-admin-database-v1', 'proto-google-cloud-speech-v1beta1']))
```

installing a correct version of oauth2client (4.1.2 doesn't match oauth2client<4.0dev,>=2.0.0) fixes this - but similar errors with other modules happen next.

the installation was done on a clean virtualenviroment

**Comment by efiop** [comment]
Feel free to reopen this issue if last pull-request didn't solve it for you.

**Comment by ophiry** [comment]
works now
