### ISSUE TITLE
dvc repro error

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#215]
```$ dvc repro
Exception caught in CmdRepro
Traceback (most recent call last):
  File "/Users/dmitry/src/dvc/dvc/main.py", line 18, in main
    ret = instance.run()
  File "/Users/dmitry/src/dvc/dvc/command/repro.py", line 50, in run
    target = self.settings.config.get('Target', None)
AttributeError: 'Config' object has no attribute 'get'```

**Comment by dmpetrov** [comment]
A similar issue with 
```$ dvc show workflow
Exception caught in CmdShowWorkflow
Traceback (most recent call last):
  File "/Users/dmitry/src/dvc/dvc/main.py", line 18, in main
    ret = instance.run()
  File "/Users/dmitry/src/dvc/dvc/command/show_workflow.py", line 14, in run
    target = self.settings.config.target_file
AttributeError: 'Config' object has no attribute 'target_file'
```
