### ISSUE TITLE
xmltotsv.py error on Python3

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#254]
'''
Error in line 0: must be str, not bytes
Traceback (most recent call last):
  File "code/xmltotsv.py", line 53, in <module>
    xmltotsv(args.input, args.output, args.extract)
  File "code/xmltotsv.py", line 29, in xmltotsv
    out.write(val.encode('ascii', 'ignore'))
TypeError: must be str, not bytes
'''

File should be opened in binary mode in xmtotsv.py.

**Comment by efiop** [comment]
Fixed in s3://dataversioncontrol/functest/code/xmltotsv.py
