### ISSUE TITLE
osx single file executable crashes

### ISSUE THREAD

**Issue by earlh** [dataversioncontrol/dvc#36]
if I run `./build_osx.sh`, the `dvc` executable crashes on startup; the relevant message seems to be

```
./dist/dvc
Traceback (most recent call last):
  File "dvc2.py", line 13, in <module>
    from dvc.command.data_import import CmdDataImport
  File "/private/var/folders/r9/4rd8csvj56s12zg3vdm360ym0000gn/T/pip-build-kSJs7p/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "dvc/command/data_import.py", line 8, in <module>
    from dvc.command.data_sync import sizeof_fmt
  File "/private/var/folders/r9/4rd8csvj56s12zg3vdm360ym0000gn/T/pip-build-kSJs7p/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "dvc/command/data_sync.py", line 6, in <module>
    from google.cloud import storage as gc
  File "/private/var/folders/r9/4rd8csvj56s12zg3vdm360ym0000gn/T/pip-build-kSJs7p/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/google/cloud/storage/__init__.py", line 35, in <module>
  File "site-packages/pkg_resources/__init__.py", line 552, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 426, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 968, in require
  File "site-packages/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
```

Probably related to
```
google/cloud/storage/__init__.py
35:__version__ = get_distribution('google-cloud-storage').version
```

**Comment by dmpetrov** [comment]
Does the tool produce executable file?
Do we need packages?
pkg for Mac
msi for windows
some binary installer for Linux
