### ISSUE TITLE
data-sync from different repo

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#51]
In a dvc repository some of data-files were synced to cloud. Then the repo was cloned.

But I failed to sync the file:
```
$ dvc data-sync data/summary.txt
Downloading cache file from S3 "nlx-shared/tag_classifier/.cache/summary.txt_6405e23"
Traceback (most recent call last):
  File "/Users/dmitry/src/dvc/dvc2.py", line 77, in <module>
    Runtime.run(CmdDataSync, args_start_loc=argv_offset)
  File "/Users/dmitry/src/dvc/dvc/runtime.py", line 45, in run
    sys.exit(instance.run())
  File "/Users/dmitry/src/dvc/dvc/command/data_sync.py", line 60, in run
    return self.sync_symlink(data_item)
  File "/Users/dmitry/src/dvc/dvc/command/data_sync.py", line 84, in sync_symlink
    self.sync_from_cloud(data_item)
  File "/Users/dmitry/src/dvc/dvc/command/data_sync.py", line 184, in sync_from_cloud
    return self._sync_from_cloud_aws(item)
  File "/Users/dmitry/src/dvc/dvc/command/data_sync.py", line 106, in _sync_from_cloud_aws
    key.get_contents_to_filename(item.resolved_cache.relative, cb=percent_cb)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 1714, in get_contents_to_filename
    os.remove(filename)
OSError: [Errno 2] No such file or directory: '.cache/summary.txt_6405e23'
```

Names are correct. File exist in the cloud.

Another issue - exception should be caught and outputted as a single line (or two lines).

**Comment by dmpetrov** [comment]
The problem was in .cache dir which was not created because there were no files.
Possible fix - create empty files when initializing the directories.
