### ISSUE TITLE
Deb package errors

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#555]
```
$ sudo dpkg -i dvc_0.9.0_amd64.deb
$ dvc --version
Traceback (most recent call last):
  File "dvc/__main__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "dvc/main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
...
```

**Comment by dmpetrov** [comment]
Also, after following dvc installation `pip install git+git://github.com/dataversioncontrol/dvc` it does not work:
```
$ dvc
-bash: /usr/bin/dvc: No such file or directory
```

The package might have issues as well.

**Comment by efiop** [comment]
Looking into it. Btw, could you please paste the full logs and not just pieces in the future? It would really save time.

**Comment by dmpetrov** [comment]
oh... sorry.
sounds good!

Do you need an access to a "clean" Linux machine? I have one running in GCP right now.

**Comment by efiop** [comment]
@dmpetrov Thank you for offering, but I already have mine setup on digitalocean. The problem there is a missing pyinstaller hook, I'll add it later today.

**Comment by efiop** [comment]
Oops, 'google-api-core' error got back. Looking into it right now.
