### ISSUE TITLE
dvc push error

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#597]
Hi,

I am facing below error while pushing my data to aws s3. It could be related to config issue. I have attached  config file as well.
[config.txt](https://github.com/dataversioncontrol/dvc/files/1866388/config.txt)

_$ dvc push -v
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\dvc\command\data_sync.py", line 36, in do_run
    self.project.push(target=target, jobs=self.args.jobs)
  File "c:\programdata\anaconda3\lib\site-packages\dvc\project.py", line 203, in push
    return self.cloud.push(self._used_cache(target), jobs)
  File "c:\programdata\anaconda3\lib\site-packages\dvc\cloud\data_cloud.py", line 115, in push
    return self._map_targets(self._cloud.push, targets, jobs, collect_local=True)
  File "c:\programdata\anaconda3\lib\site-packages\dvc\cloud\data_cloud.py", line 101, in _map_targets
    self._cloud.connect()
  File "c:\programdata\anaconda3\lib\site-packages\dvc\cloud\aws.py", line 96, in connect
    raise DataCloudError('Storage path {} is not setup correctly'.format(self.storage_bucket))
dvc.cloud.base.DataCloudError: Data sync error: Storage path dvcpoc is not setup correctly

Failed to push data to the cloud: Data sync error: Storage path dvcpoc is not setup correctly_

**Comment by efiop** [comment]
Hi @rahulguptajss !

Your config doesn't specify the Region. Could you please try specifying appropriate Region in your config and try dvc push once again? I.e. 'dvc config AWS.Region us-east-2', where 'us-east-2' should be replaced with an appropriate region for your bucket.

**Comment by rahulguptajss** [comment]
Awesome. Thanks!! It works fine now.
